import json

def get_javascript_example():
    return """fetch('https://api.example.com/data', {
  method: 'GET',
  headers: {
    'Content-Type': 'application/json'
  }
})
.then(res => res.json())
.then(data => console.log(data));
"""

def generate_openapi_spec(mock_data):
    endpoint = mock_data.get("endpoint", "https://api.example.com/data")
    method = mock_data.get("method", "GET").lower()

    base_url = endpoint.rsplit("/", 1)[0]
    path = "/" + endpoint.split("/", 3)[-1]

    spec = {
        "openapi": "3.0.0",
        "info": {
            "title": "AI Generated Public Data API",
            "version": "1.0.0",
            "description": "Auto-generated API from public data using AI"
        },
        "servers": [{"url": base_url}],
        "paths": {
            path: {
                method: {
                    "summary": "AI Generated Endpoint",
                    "responses": {
                        "200": {
                            "description": "Successful response",
                            "content": {
                                "application/json": {
                                    "schema": mock_data.get("response", {})
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    return json.dumps(spec, indent=2)

def generate_postman_collection(mock_data):
    endpoint = mock_data.get("endpoint", "https://api.example.com/data")
    method = str(mock_data.get("method", "GET")).lower()


    host_parts = endpoint.replace("https://", "").replace("http://", "").split("/")

    collection = {
        "info": {
            "name": "AI Generated API",
            "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
        },
        "item": [{
            "name": "AI Endpoint",
            "request": {
                "method": method,
                "header": [{"key": "Content-Type", "value": "application/json"}],
                "url": {
                    "raw": endpoint,
                    "host": host_parts
                }
            }
        }]
    }
    return json.dumps(collection, indent=2)

def generate_readme(mock_data):
    endpoint = mock_data.get("endpoint", "https://api.example.com/data")
    method = mock_data.get("method", "GET")
    response = mock_data.get("response", {})

    return f"""# AI Generated Public Data API

## Endpoint
`{method} {endpoint}`

## Authentication
If required, include API key in header:

```
X-API-Key: your_api_key_here
```

## Example Request

```bash
curl -X {method} "{endpoint}"
```

## Response Example

```json
{json.dumps(response, indent=2)}
```

Generated by AI API Generator
"""