
import json

def get_javascript_example():
    """Get JavaScript fetch example"""
    return """fetch('https://api.yourdomain.com/v1/indian-ipos', {
  method: 'GET',
  headers: {
    'X-API-Key': 'your_api_key_here',
    'Content-Type': 'application/json'
  }
})
.then(response => response.json())
.then(data => console.log(data));"""

def generate_openapi_spec(mock_data):
    """Generate OpenAPI specification"""
    spec = {
        "openapi": "3.0.0",
        "info": {
            "title": "Indian IPO API",
            "version": "1.0.0",
            "description": "API for accessing Indian stock market IPO data with grey market premiums"
        },
        "servers": [{"url": mock_data["endpoint"].rsplit('/', 1)[0]}],
        "paths": {
            "/indian-ipos": {
                "get": {
                    "summary": "Get IPO listings",
                    "responses": {
                        "200": {
                            "description": "Successful response",
                            "content": {
                                "application/json": {
                                    "schema": mock_data["response_structure"]
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    return json.dumps(spec, indent=2)

def generate_postman_collection(mock_data):
    """Generate Postman collection"""
    collection = {
        "info": {
            "name": "Indian IPO API",
            "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
        },
        "item": [{
            "name": "Get IPO Listings",
            "request": {
                "method": "GET",
                "header": [{"key": "X-API-Key", "value": "your_api_key_here"}],
                "url": {"raw": mock_data["endpoint"], "host": [mock_data["endpoint"]]}
            }
        }]
    }
    return json.dumps(collection, indent=2)

def generate_readme(mock_data):
    """Generate README documentation"""
    return f"""# Indian IPO API

## Endpoint
`{mock_data["endpoint"]}`

## Authentication
Include API key in header: `X-API-Key: your_api_key_here`

## Example Request
```bash
{mock_data["example_curl"]}
```

## Response Structure
```json
{json.dumps(mock_data["response_structure"], indent=2)}
```

## Rate Limiting
{mock_data["rate_limit"]}

Generated by AI API Generator
"""